name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub with latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nicor88/dbt:latest
      - name: Set tag
        run: |
          export TAG=$(cat TAG)
          echo $TAG
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nicor88/dbt:${TAG}
